### ISSUE TITLE
Error when step 4 "python experiments/SiamFC-3s-color-pretrained.py"

### ISSUE THREAD

**Issue by AydinAlptug** [bilylee/SiamFC-TensorFlow#113]
Logs folder is empty and the same error occurred with **"python experiments/SiamFC-3s-gray-pretrained.py"** too.

What am I doing wrong?

> ERROR:SiamFC-3s-color-pretrained:Failed after 0:00:00!
Traceback (most recent call last):
  File "experiments/SiamFC-3s-color-pretrained.py", line 34, in <module>
    '--enforce_clean': False,
  File "C:\Users\Yusuf\AppData\Local\Programs\Python\Python37\lib\site-packages\sacred\experiment.py", line 212, in run
    run()
  File "C:\Users\Yusuf\AppData\Local\Programs\Python\Python37\lib\site-packages\sacred\run.py", line 233, in __call__
    self.result = self.main_function(*args)
  File "C:\Users\Yusuf\AppData\Local\Programs\Python\Python37\lib\site-packages\wrapt\wrappers.py", line 567, in __call__
    args, kwargs)
  File "C:\Users\Yusuf\AppData\Local\Programs\Python\Python37\lib\site-packages\sacred\config\captured_function.py", line 48, in captured_function
    result = wrapped(*args, **kwargs)
  File "experiments\..\scripts\convert_pretrained_model.py", line 52, in main
    tf.gfile.MakeDirs(train_dir)
  File "C:\Users\Yusuf\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 438, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\Yusuf\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 453, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
**tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: Logs/SiamFC\track_model_checkpoints\SiamFC-3s-color-pretrained; No such file or directory**

**Comment by AydinAlptug** [comment]
It was a Windows related path behaviour. I resolved it by adding ../ before the path.
