### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by SaintLogos1234** [bilylee/SiamFC-TensorFlow#64]

**Comment by SaintLogos1234** [comment]
Input Test name : Starting benchmark for 1 trackers, evalTypes : ['OPE']
1_SiamFC, 1_Basketball:1/1 - OPE
failed to execute SiamFC : (<type 'exceptions.TypeError'>, TypeError("'float' object has no attribute '__getitem__'",), <traceback object at 0x7f14d0241c68>)
Traceback (most recent call last):
  File "tracker_benchmark-master/run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "tracker_benchmark-master/run_trackers.py", line 50, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "tracker_benchmark-master/run_trackers.py", line 138, in run_trackers
    butil.save_seq_result(seqResults)
  File "/home/xieyangyang/Downloads/tracker_benchmark-master/scripts/butil/load_results.py", line 9, in save_seq_result
    tracker = result[0].tracker
IndexError: list index out of range

当我进行评估时出现上述错误，是什么原因，怎么解决

**Comment by Vincent630** [comment]
can you tell me how to fix this problem because i get the same problem.just like this:
failed to execute SiamFC : (<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x7f5c60834128>)
Traceback (most recent call last):
  File "tracker_benchmark/run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "tracker_benchmark/run_trackers.py", line 50, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "tracker_benchmark/run_trackers.py", line 138, in run_trackers
    butil.save_seq_result(seqResults)
  File "/home/wenguang.wang/Downloads/tracker_benchmark/scripts/butil/load_results.py", line 9, in save_seq_result
    tracker = result[0].tracker
IndexError: list index out of range

please let me know if that is not too bother you and i will appreciate it

**Comment by Sheep-sleep-student** [comment]
I have the same problem. How did you fix it ？please help me ，thanks！
