### ISSUE TITLE
some problems when I was training

### ISSUE THREAD

**Issue by melodyhappy** [bilylee/SiamFC-TensorFlow#73]
when I run the command: python scripts/preprocess_VID_data.py
some errors occurred：
val- (0/555): Processing ILSVRC2015_val_00000000...
train-ILSVRC2015_VID_train_0001 (0/1000): Processing ILSVRC2015_train_00033007...
train-ILSVRC2015_VID_train_0000 (0/1000): Processing ILSVRC2015_train_00000000...
train-ILSVRC2015_VID_train_0003 (0/862): Processing ILSVRC2015_train_00000001...
train-ILSVRC2015_VID_train_0002 (0/1000): Processing ILSVRC2015_train_00001009...
Traceback (most recent call last):
  File "scripts/preprocess_VID_data.py", line 112, in <module>
    ans = [res.get() for res in results]
  File "scripts/preprocess_VID_data.py", line 112, in <listcomp>
    ans = [res.get() for res in results]
  File "C:\Users\mingc\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\mingc\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "scripts/preprocess_VID_data.py", line 104, in <lambda>
    one_work = lambda a, b: process_split(vid_dir, save_dir, a, b)
  File "scripts/preprocess_VID_data.py", line 90, in process_split
    context_amount=0.5, )
  File "scripts\..\utils\infer_utils.py", line 102, in get_crops
    [np.round(s_x), np.round(s_x)])
  File "scripts\..\utils\infer_utils.py", line 109, in get_subwindow_avg
    avg_chans = [np.mean(im[:, :, 0]), np.mean(im[:, :, 1]), np.mean(im[:, :, 2])]
TypeError: 'NoneType' object is not subscriptable

I don't know how to do. Can you tell me how to fix this problem? THX a lot!!!

**Comment by ectg** [comment]
Hi, How did you fix this? I am getting the same error.

**Comment by koujiaodaoyu** [comment]
> Hi, How did you fix this? I am getting the same error.
解决了吗？我也同样遇到了这个问题
