### ISSUE TITLE
ImportError: No module named 'datasets.dataloader'

### ISSUE THREAD

**Issue by deimsdeutsch** [bilylee/SiamFC-TensorFlow#79]
/opt/github2/SiamFC-TensorFlow# python3 experiments/SiamFC-3s-color-pretrained.py
Traceback (most recent call last):
  File "experiments/SiamFC-3s-color-pretrained.py", line 20, in <module>
    from scripts.convert_pretrained_model import ex
  File "/opt/github2/SiamFC-TensorFlow/scripts/convert_pretrained_model.py", line 26, in <module>
    import siamese_model
  File "/opt/github2/SiamFC-TensorFlow/siamese_model.py", line 18, in <module>
    from datasets.dataloader import DataLoader
ImportError: No module named 'datasets.dataloader'

**Comment by bilylee** [comment]
Did you have "SiamFC-TensorFlow/datasets/dataloader.py" in your directory? 

Moreover, Please note that the repo is developed under python2. I am not sure if it works under python3.
