### ISSUE TITLE
运行otb评估时出错了。

### ISSUE THREAD

**Issue by yangkang779** [bilylee/SiamFC-TensorFlow#8]
yangkang@node1:~$ echo "tb50" | python tracker_benchmark/run_trackers.py -t SiamFC -s tb50 -e OPE                      Traceback (most recent call last):
  File "tracker_benchmark/run_trackers.py", line 6, in <module>
    from scripts import *
  File "/home/yangkang/tracker_benchmark/scripts/__init__.py", line 2, in <module>
    from bscripts import *
  File "/home/yangkang/tracker_benchmark/scripts/bscripts/__init__.py", line 24, in <module>
    from run_SiamFC import *
  File "/home/yangkang/tracker_benchmark/scripts/bscripts/run_SiamFC.py", line 19, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /usr/local/MATLAB/MATLAB_Production_Server/R2015a/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

我按照这个方法解决可是没有成功，还是失败，ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6  /usr/local/MATLAB/MATLAB_Production_Server/R2015a/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../sys/os/glnxa64/libstdc++.so.6
谢谢。单纯运行benchmark的话运行到第一个视频自动结束就报错了，outlist好像

**Comment by bilylee** [comment]
试试这里的方法？

https://stackoverflow.com/questions/35953210/error-running-basic-tensorflow-example

**Comment by yangkang779** [comment]
ImportError: /usr/local/MATLAB/MATLAB_Production_Server/R2015a/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
yangkang@node1:~$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python import pywrap_tensorflow
>>>

试过了，应该是MATLAB里libstdc++.so.6: version `GLIBCXX_3.4.19' not found的问题。我再查查

**Comment by yangkang779** [comment]
2_SCM, 1_Basketball:1/1 - OPE
Starting matlab engine...
Undefined function or variable 'vgg_kmiter'.

Error in vgg_kmeans (line 31)
    [CX, sse] = vgg_kmiter(X, CX);

Error in formCodebookL (line 32)
[centers,sse] = vgg_kmeans(double(descriptors), codebook_size, cluster_options);

Error in affineTrainL (line 48)
Fi = formCodebookL(patch, Fisize);      % form the dictionary

Error in run_SCM (line 57)
[Fio patcho] = affineTrainL(img, param0, opt, patchsize, patchnum, Fisize);

failed to execute SCM : (<class 'matlab.engine.MatlabExecutionError'>, MatlabExecutionError("\n  File /home/yangkang/tracker_benchmark/trackers/SCM/vgg_kmeans.m, line 31, in vgg_kmeans\n\n  File /home/yangkang/tracker_benchmark/trackers/SCM/formCodebookL.m, line 32, in formCodebookL\n\n  File /home/yangkang/tracker_benchmark/trackers/SCM/Affine Sample Functions/affineTrainL.m, line 48, in affineTrainL\n\n  File /home/yangkang/tracker_benchmark/trackers/SCM/run_SCM.m, line 57, in run_SCM\nUndefined function 'vgg_kmiter' for input arguments of type 'double'.\n",), <traceback object at 0x7f50404e9518>)
Traceback (most recent call last):
  File "run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "run_trackers.py", line 50, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "run_trackers.py", line 138, in run_trackers
    butil.save_seq_result(seqResults)
  File "/home/yangkang/tracker_benchmark/scripts/butil/load_results.py", line 9, in save_seq_result
    tracker = result[0].tracker
IndexError: list index out of range

你好，请问这个报错是因为版本问题么？我用的是matlab2015a  
看到有人评论说Works on Matlab 2015b and Matlab 2016a.你的用的是多少呀？我怕不是由于那个

**Comment by bilylee** [comment]
不确定是不是版本原因啊。你可以这个 try block 去掉，查看更精细的 log 信息

https://github.com/bilylee/tracker_benchmark/blob/3dd07b14cfa7c6bdc13365026cf749cdffd2e7a6/run_trackers.py#L117

我用的是 Matlab 2016a。

**Comment by yangkang779** [comment]
Undefined function or variable 'vgg_kmiter'.

Error in vgg_kmeans (line 31)
    [CX, sse] = vgg_kmiter(X, CX);

Error in formCodebookL (line 32)
[centers,sse] = vgg_kmeans(double(descriptors), codebook_size, cluster_options);

Error in affineTrainL (line 48)
Fi = formCodebookL(patch, Fisize);      % form the dictionary

Error in run_SCM (line 57)
[Fio patcho] = affineTrainL(img, param0, opt, patchsize, patchnum, Fisize);

Traceback (most recent call last):
  File "run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "run_trackers.py", line 50, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "run_trackers.py", line 118, in run_trackers
    res = eval(funcName)
  File "<string>", line 1, in <module>
  File "/home/yangkang/tracker_benchmark/scripts/bscripts/run_SCM.py", line 15, in run_SCM
    res = m.eval(func, nargout=1)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 79, in __call__
    _stderr).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 107, in result
    self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError:
  File /home/yangkang/tracker_benchmark/trackers/SCM/vgg_kmeans.m, line 31, in vgg_kmeans

  File /home/yangkang/tracker_benchmark/trackers/SCM/formCodebookL.m, line 32, in formCodebookL

  File /home/yangkang/tracker_benchmark/trackers/SCM/Affine Sample Functions/affineTrainL.m, line 48, in affineTrainL

  File /home/yangkang/tracker_benchmark/trackers/SCM/run_SCM.m, line 57, in run_SCM
Undefined function 'vgg_kmiter' for input arguments of type 'double'.
把try 模块去了出现了这个，我再2015上也有报错的，不是版本问题，
运行时例程python run_trackers.py -t IVT,TLD -s Couple,Crossing -e OPE,SRE也会出现错误，CT算法的话不会报错Error in run_TLD (line 40)
[bb,conf,fps] = tldExample(para);

Traceback (most recent call last):
  File "run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "run_trackers.py", line 50, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "run_trackers.py", line 118, in run_trackers
    res = eval(funcName)
  File "<string>", line 1, in <module>
  File "/home/yangkang/tracker_benchmark/scripts/bscripts/run_TLD.py", line 15, in run_TLD
    res = m.eval(func, nargout=1)
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/matlabengine.py", line 79, in __call__
    _stderr).result()
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/futureresult.py", line 107, in result
    self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError:
  File /home/yangkang/tracker_benchmark/trackers/TLD/tld/tldInit.m, line 20, in tldInit

  File /home/yangkang/tracker_benchmark/trackers/TLD/tld/tldExample.m, line 31, in tldExample

  File /home/yangkang/tracker_benchmark/trackers/TLD/run_TLD.m, line 40, in run_TLD
Undefined function 'lk' for input arguments of type 'double'.
谢谢指导啊，我最近都在做这个方面的工作，因为刚刚接触不久，不太熟悉，谢谢啊

**Comment by yangkang779** [comment]
难道时python 的matlab接口不止 python setup.py install?命令？还要配置什么么？我觉得好像基准的配置有点问题

**Comment by yangkang779** [comment]
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
我把这个命令 j加入。gedit ~/.bashrc  最后一行，然后source ~/.bashrc就解决了，因为要求ys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found    GLIBCXX_3.4.19 而我的只有3.4.17，就把libstdc++加入进来了。谢谢作者，可以评估SiamFC这个了。

**Comment by bilylee** [comment]
能评估就好 ：）
