### ISSUE TITLE
运行SiamFC-3s-color-pretrained.py出错

### ISSUE THREAD

**Issue by stillqueen** [bilylee/SiamFC-TensorFlow#83]
环境是python 3.6，TF1.6，在pycharm上运行的
WARNING - SiamFC-3s-color-pretrained - No observers have been added to this run
INFO - SiamFC-3s-color-pretrained - Running command 'main'
INFO - SiamFC-3s-color-pretrained - Started
INFO - root - Restore from last checkpoint: Logs/SiamFC\track_model_checkpoints\SiamFC-3s-color-pretrained\model.ckpt-0
INFO:tensorflow:Restoring parameters from Logs/SiamFC\track_model_checkpoints\SiamFC-3s-color-pretrained\model.ckpt-0
INFO - tensorflow - Restoring parameters from Logs/SiamFC\track_model_checkpoints\SiamFC-3s-color-pretrained\model.ckpt-0
ERROR - SiamFC-3s-color-pretrained - Failed after 0:00:01!
Traceback (most recent call last):
  File "D:/pylearn/SiamFC-TensorFlow-master/experiments/SiamFC-3s-color-pretrained.py", line 32, in <module>
    '--enforce_clean': False,
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\sacred\experiment.py", line 209, in run
    run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\sacred\run.py", line 221, in __call__
    self.result = self.main_function(*args)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\sacred\config\captured_function.py", line 46, in captured_function
    result = wrapped(*args, **kwargs)
  File "D:\pylearn\SiamFC-TensorFlow-master\scripts\convert_pretrained_model.py", line 92, in main
    start_step =int(tf.train.global_step(sess, model.global_step.name) + 1)
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by ectg** [comment]
I have been getting the same error too. Does anyone have a solution? Thanks!

**Comment by xxcheng0708** [comment]
The function of SiamFC-3s-color-pretrained.py is convert mat file of matlab to checkpoint file of tensorflow,so when you run  SiamFC-3s-color-pretrained.py, Logs/SiamFC/track_model_checkpoints/SiamFC-3s-color-pretrained/model.ckpt-0 would be created,you should run  SiamFC-3s-color-pretrained.py only once.

**Comment by bilylee** [comment]
@xxcheng0708 is right. 

Please check if `Logs/SiamFC/track_model_checkpoints/SiamFC-3s-color-pretrained\model.ckpt-0` exists.
