### ISSUE TITLE
Runing error when i try 'python experiments/SiamFC-3s-color-pretrained.py'

### ISSUE THREAD

**Issue by JameesWang** [bilylee/SiamFC-TensorFlow#88]
WARNING - SiamFC-3s-color-pretrained - No observers have been added to this run
INFO - SiamFC-3s-color-pretrained - Running command 'main'
INFO - SiamFC-3s-color-pretrained - Started
INFO:tensorflow:Creating training directory: Logs/SiamFC\track_model_checkpoints\SiamFC-3s-color-pretrained
INFO - tensorflow - Creating training directory: Logs/SiamFC\track_model_checkpoints\SiamFC-3s-color-pretrained
ERROR - SiamFC-3s-color-pretrained - Failed after 0:00:00!
Traceback (most recent call last):
  File "experiments/SiamFC-3s-color-pretrained.py", line 32, in <module>
    '--enforce_clean': False,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sacred\experiment.py", line 209, in run
    run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sacred\run.py", line 221, in __call__
    self.result = self.main_function(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sacred\config\captured_function.py", line 46, in captured_function
    result = wrapped(*args, **kwargs)
  File "experiments\..\scripts\convert_pretrained_model.py", line 52, in main
    tf.gfile.MakeDirs(train_dir)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 442, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 458, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path), status)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: Logs/SiamFC\track_model_checkpoints\SiamFC-3s-color-pretrained; No such file or directory

I am a beginner. Thank for your advice!

**Comment by JameesWang** [comment]
i have solved this problems.
Create ‘SiamFC’ folder in the ‘Log’ folder, then create 'track_model_checkpoints'  folder in the 'SiamFC' folder.
it is a easy probelem i guess.Hope it helps you！
Thank you.
