### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.convert_pretrained_model'

### ISSUE THREAD

**Issue by zpsandzzc** [bilylee/SiamFC-TensorFlow#90]
运行SiamFC-3s-color-pretrained.py出错，ModuleNotFoundError？？？但是scripts.convert_pretrained_model可以点开
runfile('C:/Users/pc/SiamFC-TensorFlow-master/experiments/SiamFC-3s-color-pretrained.py', wdir='C:/Users/pc/SiamFC-TensorFlow-master/experiments')
Traceback (most recent call last):

  File "<ipython-input-1-11a8f5088cf5>", line 1, in <module>
    runfile('C:/Users/pc/zzccode/SiamFC-TensorFlow-master/experiments/SiamFC-3s-color-pretrained.py', wdir='C:/Users/pc/zzccode/SiamFC-TensorFlow-master/experiments')

  File "C:\Users\pc\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\pc\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/pc/zzccode/SiamFC-TensorFlow-master/experiments/SiamFC-3s-color-pretrained.py", line 20, in <module>
    from scripts.convert_pretrained_model import ex

ModuleNotFoundError: No module named 'scripts.convert_pretrained_model'

**Comment by bilylee** [comment]
working directory 应该是 `C:/Users/pc/zzccode/SiamFC-TensorFlow-master`。

请尝试执行：
```
runfile('C:/Users/pc/zzccode/SiamFC-TensorFlow-master/experiments/SiamFC-3s-color-pretrained.py', 
wdir='C:/Users/pc/zzccode/SiamFC-TensorFlow-master')
```
