### ISSUE TITLE
在Benchmark的第六步的时候会出现这种错误/ why does this error occur in step 6 of benchmark

### ISSUE THREAD

**Issue by Fine0708** [bilylee/SiamFC-TensorFlow#99]
Professor, why does this error occur in step 6 of benchmark：
failed to execute SiamFC : (<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x00000000265F8188>) Traceback (most recent call last): File "tracker_benchmark/run_trackers.py", line 146, in <module> main(sys.argv[1:]) File "tracker_benchmark/run_trackers.py", line 50, in main trackers, seqs, evalType, shiftTypeSet) File "tracker_benchmark/run_trackers.py", line 138, in run_trackers butil.save_seq_result(seqResults) File "D:\tracker_benchmark\scripts\butil\load_results.py", line 9, in save_seq_result tracker = result[0].tracker IndexError: list index out of range 
Please help me, thanks very much！

**Comment by ghost** [comment]
请问你解决了没？我现在做到这一步也出现了问题

**Comment by ghost** [comment]
我现在出现的error是：echo "tb100" | python tracker_benchmark/run_trackers.py -t SiamFC -s tb100 -e OPE
Traceback (most recent call last):
  File "tracker_benchmark/run_trackers.py", line 6, in <module>
    from tracker_benchmark.scripts import *
ImportError: No module named 'tracker_benchmark'
但是在pycharm里面运行没有错

**Comment by bilylee** [comment]
报错上来看某些文件没有找到。请确认一下：模型文件、OTB数据集等是否存在？是否严格按照 README 的步骤在 terminal 中执行？
